# Universidad Autonoma de Aguascalientes
# Carrera: Ingenieria en Computación Inteligente
# Curso: Aprendizaje Inteligente
# Maestro: Dr. Francisco Javier Luna Rosas
# Alumno: Martin Isai Nunez Villeda
# Semestre: Enero-Junio del 2026

### Practica No. 4: El Perceptron de Frank Rosenblatt

##### Un perceptrón es un tipo de modelo de red neuronal muy simple, utilizado principalmente para problemas de clasificación binaria. Fue desarrollado en 1958 por Frank Rosenblatt y es considerado uno de los primeros algoritmos de aprendizaje supervisado.

##### Un perceptrón toma un conjunto de entradas, las procesa mediante una serie de operaciones matemáticas y produce una salida que puede ser 0 o 1, dependiendo de si el resultado final supera un umbral predeterminado.

##### En esta practica vamos a determinar si se le aprueba o no, una tarjeta de credito a un cliente, considerando la edad y el ahorro que tiene en su cuanta bancaria.

## Paso 1: Importar las librerías necesarias

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Paso 2: Generar los datos (Dataset)

In [2]:
personas = np.array([[0.3, 0.4], [0.4, 0.3], 
                     [0.3, 0.2], [0.4, 0.1], 
                     [0.5, 0.4], [0.4, 0.8], 
                     [0.6, 0.8], [0.5, 0.6], 
                     [0.7, 0.6], [0.8, 0.5]])

## Paso 3: Definir las clases: 1 = aprobado : 0 = denegado 

In [3]:
clases = np.array([0,0,0,0,0,1,1,1,1,1])

## Paso 4: Definir la función de activación

In [4]:
def activacion(pesos, x, b):
    z = pesos * x
    if z.sum() + b > 0:
        return 1
    else:
        return 0

## Paso 5: Generamos los pesos y el bias

In [5]:
pesos = np.random.uniform(-1,1, size = 2)
b = np.random.uniform(-1,1)
pesos, b, activacion(pesos, [0.8, 0.5], b)

(array([ 0.16240014, -0.3307598 ]), -0.2578848079479341, 0)

## Paso 6: Importamos el Algoritmo del Perceptrón

In [6]:
pesos = np.random.uniform(-1,1, size = 2)
b = np.random.uniform(-1,1)
tasa_de_aprendizaje = 0.01
epocas = 100

#Ciclo de entrenamiento

for epoca in range(epocas):
    error_total = 0
    for i in range(len(personas)):
        prediccion = activacion(pesos, personas[i], b)
        error = clases[i] - prediccion
        error_total += error**2
        pesos[0] += tasa_de_aprendizaje * personas[i][0] * error
        pesos[1] += tasa_de_aprendizaje * personas[i][1] * error
        b += tasa_de_aprendizaje * error
    print(error_total, end = " ")

5 5 5 5 5 6 7 6 7 5 5 6 5 5 4 4 5 4 5 3 2 2 4 3 2 2 3 2 2 2 1 2 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

## Paso 7: Probar el algoritmo

In [7]:
pesos, b, activacion(pesos, [0.3, 0.4], b)

(array([-0.00923619,  0.09791461]), np.float64(-0.03972308350920295), 0)

In [8]:
pesos, b, activacion(pesos, [0.8, 0.5], b)

(array([-0.00923619,  0.09791461]), np.float64(-0.03972308350920295), 1)

## Conclusiones

##### En esta practica entrenamos el algoritmo del preceptron para determinar si se le aprueba o no una tarjeta de credito a un cliente, considerando la edad y el ahorro que tiene en su cuenta bancariaq

## Referencias

#### [1] SCIKIT-LEARN (Machine Learning in Python 2025). URL https://scikit-learn.org/stable/ (Último acceso, Febrero de 2026).

#### [2] Octavio Gutiérrez (2025). El Perceptron Paso a Paso con Python: https://www.youtube.com/watch?v=dkhXGTersP0 (Último acceso, Febrero de 2026)

#### [3] Sebastian Raschka, Vahid Mirjalili (2019). Machine Learning, Editorial Marcombo, Madrid, España. URL: www.marcombo.info ISBN: 978-84-267-2720-6