## Universidad Autonoma de Aguascalientes
## Carrera: Ingenieria en Computación Inteligente 
## Curso: Aprendizaje Inteligente
## Maestro: Dr. Francisco Javier Luna Rosas
## Alumno: Martin Isai Nunez Villeda
## Semestre: Enero-Junio del 2026

# Practica 6: Redes Neuronales (SCIKIT-LEARN_MPLClassifier)
### En esta práctica implementaremos un modelo de clasificación utilizando una red neuronal con técnica de propagación hacia atrás (por sus siglas en el idioma Inglés NNBP). La NNBP se implementará utilizando la librería de código abierto SCIKIT-LEARN.

## Paso 1: Importar las librerias necesarias

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

## Paso 2: Cargamos el dataset

In [ ]:
os.chdir("C:/Users/sebsa/Downloads")
datos = pd.read_csv('iris.csv', delimiter=';', decimal=".")
print(datos.shape)
print(datos.head())
#print(datos.info())

(150, 5)
   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa


## Paso 3: Elimina la variable categórica, deja las variables predictoras en X

In [ ]:
X = datos.iloc[:,:4]
print(X.head())

   s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2


## Paso 4: Deja la variable a predecir en Y

In [ ]:
y = datos.iloc[:, 4:5]
print(y.head())

     tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa


## Paso 5: Se separan los datos con el 70% de los datos para entrenamiento y el 30% para testing

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, random_state = 0)

## Paso 6: Mediante el constructor inicializa la instancia_red

In [ ]:
instancia_red = MLPClassifier()
print(instancia_red)

MLPClassifier()


## Paso 7: Entrena el modelo llamando al método fit

In [ ]:
instancia_red.fit(X_train, y_train.iloc[:,0].values)

C:\Users\sebsa\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

## Paso 8: Imprime las predicciones en testing

In [ ]:
print("Las predicciones en Testing son: {}".format(instancia_red.predict(X_test)))

Las predicciones en Testing son: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'virginica' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'virginica'
 'setosa' 'setosa']


## Paso 9: Función para calcular los índices de calidad de la predicción

In [ ]:
def indices_general(MC, nombres = None):
    precision_global = np.sum(MC.diagonal()) / np.sum(MC)
    error_global = 1 - precision_global
    precision_categoria = pd.DataFrame(MC.diagonal() / np.sum(MC, axis = 1)).T
    if nombres!=None:
        precision_categoria.columns = nombres
    return {
            "Matriz de Confusión":MC,
            "Precisión Global": precision_global,
            "Error Global":error_global,
            "Precisión por categoría":precision_categoria
           }

## Paso 10: Índices de Calidad del Modelo

In [ ]:
prediccion = instancia_red.predict(X_test)
MC = confusion_matrix(y_test, prediccion)
indices = indices_general(MC, list(np.unique(y)))
for k in indices:
    print("\n%s: \n%s "%(k, str(indices[k])))


Matriz de Confusión: 
[[16  0  0]
 [ 0 16  2]
 [ 0  0 11]] 

Precisión Global: 
0.9555555555555556 

Error Global: 
0.0444444444444444 

Precisión por categoría: 
   setosa  versicolor  virginica
0     1.0    0.888889        1.0 


## Conclusiones:
### En esta práctica utilizamos un algoritmo de aprendizaje automático conocido como machine learning para clasificar clases que son no lineales, utilizamos una Neuronal Networks Backward Propagation o NNBP. Las NNBP calsifica diferentes especies de la flor de iris: setosa, versicolor, y virginica. Las caracteristicas que se tomaron en cuenta son: longitud y ancho del pétalo, y la longitud y ancho del séfalo.

## Referencias
### Russell S.J., Norvig P. (2020). Artifical Intelligence: A Modern Approach, Prentine-Hall, 4th Edition, Englewood Cliffs, NJ, 2020.
### Kevin (2025). NEURONA DEl Modelo de McCulloch Pitts. https://www.youtube.com/watch?v=ROErFR3X4x0 (Ultimo acceso Febrero 2025)
### OpenAI. (2025). ChatGPT (modelo GPT-5.2)[Modelo de lenguaje grande].https://chatgpt.com/